on:
  push:
    branches: [main]
name: 🚀 Deploy React App to Production
jobs:
  setup:
    name: 📌 Setup build process
    runs-on: ubuntu-latest
    steps:
      - name: ⏩ Checkout latest code
        uses: actions/checkout@v2.3.2
      - name: 🌟 Setup Node.js 14
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: ⬇ Install dependencies
        run: yarn install

  build:
    name: 🔨 Build React App
    runs-on: ubuntu-latest
    steps:
      - name: 🧾 Execute build script
        run: yarn build
        env:
          REACT_APP_SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}

  deploy:
    name: 🗂 Deploy production build
    runs-on: ubuntu-latest
    steps:
      - name: ⬆ Upload build folder to production server
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: 45.85.219.34
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          METHOD: sftp
          PORT: 22
          LOCAL_DIR: build
          REMOTE_DIR: /var/www/composer
          ARGS: --delete