# This workflow will list all npm packages and their licenses in this repository using npx license-checker
name: list-packages
on:
  push:
    branches:
      - develop
      - staging
      - spike/workflows
      - main
jobs:
  list-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install

      - name: Install license-checker
        run: npm install license-checker

      - name: List packages
        run: npx license-checker --production
